//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager
    {
        public int ManagerID { get; set; }
        public Nullable<int> EmployeID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> LevelID { get; set; }
    
        public virtual tblEmploye tblEmploye { get; set; }
        public virtual tblLevel tblLevel { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
