//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportID { get; set; }
        public Nullable<int> EmployeID { get; set; }
        public string EmployeName { get; set; }
        public string EmployeSurname { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string Project { get; set; }
        public string Position { get; set; }
        public Nullable<int> Hourst { get; set; }
    
        public virtual tblEmploye tblEmploye { get; set; }
    }
}
